version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - NLP_SECRET_KEY=devsecretkey
      - NLP_DB_HOST=192.168.1.169
      - NLP_DB_NAME=${NLP_DB_NAME}
      - NLP_DB_USER=${NLP_DB_USER}
      - NLP_DB_PASS=${NLP_DB_PASS}
      - NLP_ALLOWED_HOSTS=${NLP_ALLOWED_HOSTS}
    depends_on:
      - db
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - NLP_POSTGRES_DB=${NLP_DB_NAME}
      - NLP_POSTGRES_USER=${NLP_DB_USER}
      - NLP_POSTGRES_PASSWORD=${NLP_DB_PASS}