version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db
    command: >
      sh -c "python app/manage.py wait_for_db &&
             python app/manage.py migrate &&
             python app/manage.py runserver 0.0.0.0:8080"
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}